apiVersion: apps/v1
kind: Deployment
metadata:
  name: network-multitool
  labels:
    app: multitool
spec:
  replicas: 2
  selector:
      matchLabels:
        app: multitool
  template:
    metadata:
      annotations:
        co.elastic.logs/enabled: 'true'
      labels:
        app: multitool
        internal: ingress
        internal-ingress-http: allow
        workstations: ingress
        workstations-ingress-http: allow
    spec:
      containers:
      - name: network-multitool
        image: registry.svc.intranet/l-pd-kubernetes/praqma-network-multitool
        resources:
          limits:
            memory: "100Mi"
            cpu: "50m"
          requests:
            memory: "50Mi"
            cpu: "20m"
---
apiVersion: v1
kind: Service
metadata:
  name: multitool
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: multitool
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-multitool
spec:
  ingressClassName: ingress-controller-internal
  rules:
  - host: multitool.intranet
    http:
      paths:
      - backend:
          service:
            name: multitool
            port:
              number: 80
        path: /
        pathType: Prefix