apiVersion: apps/v1
kind: Deployment
metadata:
  name: network-multitool
  labels:
    app: multitool
spec:
  replicas: 2
  selector:
      matchLabels:
        app: multitool
  template:
    metadata:
      labels:
        app: multitool
        internal: egress
        internal-egress-http: allow
        internal-egress-https: allow
        workstations: ingress
        workstations-ingress-http: allow
    spec:
      containers:
      - name: network-multitool
        image: wbitt/network-multitool
        resources:
          requests:
            memory: "10Mi"
            cpu: "10m"
          limits:
            memory: "20Mi"
            cpu: "20m"
---
apiVersion: v1
kind: Service
metadata:
  name: multitool
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: multitool
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: multitool-ingress
spec:
  ingressClassName: ingress-controller-internal
  rules:
  - host: multitool.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: multitool
            port:
              number: 80
